import logging

from rapidfuzz import process, fuzz

employee_names = [
"AARON MALVERN DANN",
"ALLAN PEREIRA DA SILVA",
"ALECSANDRA TEIXEIRA CUNHA",
"ANGELA MARGARIDA MONTEIRO DIAS BRANCO",
"ANA ALICE BONIFACIO LEITE",
"ANA CRISTINA DE CARVALHO SOUZA",
"ANA GABRIELA DE MELLO LAUER",
"ANA MARIA CASTELO BRANCO",
"ANA PAULA REZENDE GONCALVES",
"ARTHUR BARRAGAN VASCONCELOS",
"AILTON TORRES DE SOUZA",
"ANTÔNIO AUGUSTO FERREIRA DE BRITO",
"CARSTEN WEGENER",
"CLARISSE ARAUJO GURGEL",
"DANIEL OLUWAGBOTEMI FASHEUN",
"DANIELLE S. LUZ",
"DAX NOLDING",
"DENISE MARIA AFONSO GOMES DA SILVA",
"DIOGO GUIMARAES MULDER",
"ELAINE FERRARI ANTUNES",
"ELISABETE BARCELLOS DE SOUZA LAPA",
"ELVIRA MARIA DE MOURA REALEIRO",
"ELIANE PIMENTEL RIBEIRO",
"FAUSTO DE OLIVEIRA DE MOURA",
"FERNANDO CANAZIO AMORIM",
"GIOVANA BRANCO CARNEIRO",
"GRACIETE OLIVEIRA DE MOURA",
"GUILHERME DE MELLO GONÇALVES",
"IDA DE FATIMA GARRITANO M. GUIMARÃES",
"ISABELA BATISTA OLIVA",
"IVONE VIEIRA",
"JORGELINA ELECTRA FLORES",
"JUDITH PATRICIA BRANDT",
"JULIANA MANCZENKO CHAGAS",
"JULIANE CARVALHO DANTAS",
"KELVIN DANIEL",
"LEANA AYMORE JACOB",
"LEONARDO DE CASTRO F. SILVA",
"LUCIANE ALVES FERNANDEZ",
"LUIZA ANTONIA FIGUEIREDO",
"MAIRA SOBROSA CORDEIRO",
"MARCO ADRIAN CABALLERO",
"MARCO GOMES DA SILVA",
"MARIANELA VASQUEZ",
"MARCIA PATRIZIO SANTOS",
"MATHEUS MARINS MONTEIRO DE BARROS",
"MAXIMINO MATIAS DELGADO",
"MERCEDES ISABEL PAGOLA",
"MONICA ESTHER BACA COAQUIRA",
"MONIK BAIMA REGO DE AZEVEDO",
"MÔNICA PAULO FERREIRA",
"NADJA DIAS GONÇALVES DE FRANÇA",
"NTULA BOIKA",
"ONESSIMO BAGNO DA SILVA",
"PATRICIA DO CARMO FERRAZ",
"PATRICIA VIDAL",
"PATRICK RESENDE NASCIMENTO",
"PEDRO PONTES",
"PRISCILA NOGUEIRA DA ROCHA",
"PRISCILA TEIXEIRA DE SOUZA",
"RAFAEL DE CASTRO FIGUEIRA SILVA",
"RAFAEL GOMEZ",
"RENE BRANQUINHO",
"RICARDO GOMES DA SILVA MILANEZ",
"ROBERTO RAQUEL SILVA DE OLIVEIRA",
"ROBERT DOUGLAS DE SÁ QUEEN",
"RODNEY EDUARDO GONCALVES OUREM",
"RODRIGO DA SILVA",
"ROGERIO FERREIRA SAMPAIO",
"ROSIANE TAVARES GONCALVES",
"SANDRA ALMEIDA MARCHATTO",
"TATIANA ALVES RANGEL",
"TATIANA CORREIA DOS SANTOS",
"TATIANA RANGEL PARETO DE CICCO",
"TANIA SOIBELMAN",
"THAIS AFFONSO DE ALVARENGA",
"VERA REGINA DE OLIVIERA SERRA",
"VITÓRIA SANTANA ANHETTI",
"WAGNER RIBEIRO ANGELO",
"YANN NORMAN CHARLES"
]


logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(message)s",
    datefmt="%d-%m-%Y %H:%M:%S")


    # Função para identificar se um nome da planilha está presente no texto extraído
def identify_employee_name(text, employee_list):
    """
    Identifica o nome de um funcionário no texto extraído.
    """
    logging.info("Texto recebido para identificação: '%s'", text)
    text_lower = text.lower()
    for name in employee_list:
        if name.lower() in text_lower:
            logging.debug("Nome encontrado: '%s'", name)
            return name
    return "Desconhecido"

